relocate hikari
MartenM/ServerTutorialPlus pull request #61
Opened 2021-11-28 14:49 UTC by kacperleague9

2021-11-28 16:49 UTC, MartenM commented
Hey!

Thanks for submitting a PR request. 
I can see how it would be neat to shade it like this but what exactly would be the benefits?

2021-11-28 17:12 UTC, kacperleague9 commented
Fixes libertybans crashing on startup

2021-11-28 17:46 UTC, MartenM commented
Ah, could you show me the stack trace for that?
Kinda interested in why that would happen :)

2021-11-29 16:03 UTC, kacperleague9 commented
its because it uses some rare depedency injecting lib i think

2021-12-08 20:26 UTC, kacperleague9 commented
everyone i asked tells me that it should be always relocated

2021-12-11 21:14 UTC, MartenM approved these changes

2021-12-12 12:11 UTC, MartenM requested changes

2021-12-12 12:11 UTC, MartenM commented on pom.xml
> +                        <shadedPattern>nl.marten.libs.hikari</shadedPattern>
Build the project on my machine and noticed that this should be `nl.martenm` instead of  `nl.marten`. As soon as you change this I will merge the PR :)

2021-12-12 21:27 UTC, MartenM approved these changes

2021-12-12 21:28 UTC, merged