Significant plugin.yml & misc. updates
MartenM/ServerTutorialPlus pull request #63
Opened 2021-12-17 01:45 UTC by Tsuser1

This pull request includes significant changes to the plugin.yml being included. These changes were implemented for the benefit of those using modern permissions management plugins, such as LuckPerms, which include information derived from the plugin.yml permissions. Additionally, there were minor changes made to pom.xml to allow building without needing to manually include external libraries, and the renaming of one class to be in-line with Java best practices.

Full changelog:

1. Updated .gitignore to include commonly mis-committed files
2. Fixed plugin.yml and added permission description tags for modern permissions plugins to display. Also added the api-version.
3. Updated pom.xml to include missing libraries and to update the archaic Spigot 1.12.2 API to Spigot 1.18 (latest stable version).
4. Renamed onPlayerMoveEvent to OnPlayerMoveEvent

2021-12-17 02:04 UTC, Tsuser1 commented
**New commit added: Modernized README.md**

Made the readme look much nicer.

2021-12-17 02:16 UTC, Tsuser1 commented
**New commit added: Fixed outdated Material**

Fixed an outdated reference to `Materal.FIREWORK` by replacing with the equivalent `Material.FIREWORK_ROCKET`.

2021-12-17 03:23 UTC, Tsuser1 commented
**Many patches, bugfixes, and lots of code review**

Review commits to see individual small fixes. The only one of major note is 95d6eea where a potential NullPointerException is fixed.

2021-12-17 11:57 UTC, MartenM commented
Hey!

Thanks for your contributions to the project. I will look into this as soon as possible.

2021-12-18 20:43 UTC, MartenM commented
I plan on removing support for everything lower then 1.12.
Do you know how these changes affect other versions? I considered using XMaterial for this project but haven't gotten around to implement it yet.

2021-12-19 20:18 UTC, MartenM requested changes
Overall pretty okay changes. However, I wonder what this does for the plugins compatibility.
I don't want to quite drop support for 1.12 since 15% of the plugins are running on 1.12 servers.

2021-12-19 20:18 UTC, MartenM commented on src/main/java/nl/martenm/servertutorialplus/ServerTutorialPlus.java
> +        //MetricsLite metricsLite = new MetricsLite(this);
The metrics class is not unused and is reporting correctly to bstats.org
https://bstats.org/plugin/bukkit/ServerTutorialPlus/382

2021-12-19 20:18 UTC, MartenM commented on src/main/java/nl/martenm/servertutorialplus/objects/NPCInfo.java
> +	public ServerTutorialPlus getPlugin() {
What is the use of putting a getter for the plugin instance here?

2021-12-19 20:18 UTC, MartenM commented on src/main/java/nl/martenm/servertutorialplus/managers/clickactions/ClickManager.java
> +	public ServerTutorialPlus getPlugin() {
What is the use of getPlugin() here? If people want a plugin instance they should get it using the plugin manager or from the main plugin class.

2021-12-19 20:18 UTC, MartenM commented on src/main/java/nl/martenm/servertutorialplus/helpers/MetricsLite.java
> -@SuppressWarnings({"unchecked", "Convert2Lambda"})
Please don't touch this class. This was the original MetricsLite class from BStats.
I will update this my self in another PR to be more up-to-date.

2021-12-19 20:18 UTC, MartenM commented on src/main/java/nl/martenm/servertutorialplus/events/OnPlayerInteractEventV1_8.java
> +                event.getPlayer().sendMessage(Lang.ERROR_FAILED_FINDING_TUTORIAL_ADMIN.toString().replace("%id%", "NULL_ID"));
"NULL_ID"  should be `ts.ServerTutorialId`. Good catch finding this NPE though.

2021-12-19 20:18 UTC, MartenM commented on .settings/.gitignore
> +/org.eclipse.jdt.core.prefs
I did rather not have the .settings folder in the GitHub directory.

2023-10-03 11:22 UTC, closed without merging