adding placeholders for other plugin
MartenM/ServerTutorialPlus pull request #78
Opened 2023-09-30 08:41 UTC by alan67160

`%servertutorialplus_getTutorial%`
get the current tutorial ID
return null if no tutorial are playing or player offline
`%servertutorialplus_getPoints%`
get the current point index
return null if no tutorial are playing or player offline
`%servertutorialplus_getMaxPoints%`
get the max point index for the current tutorial
return null if no tutorial are playing or player offline

2023-09-30 08:44 UTC, alan67160 commented
btw you can request to add this plugin on https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Plugins-using-PlaceholderAPI#s

2023-09-30 09:54 UTC, MartenM requested changes
Solid contribution apart from that one issue!

2023-09-30 09:54 UTC, MartenM commented on src/main/java/nl/martenm/servertutorialplus/managers/PlaceholderapiManager.java
> +public class PlaceholderapiManager extends PlaceholderExpansion {
Please change the name to something like: ServertutorialPlaceholderExpansion.
It's not really an API manager class.

2023-09-30 10:23 UTC, alan67160 commented on src/main/java/nl/martenm/servertutorialplus/managers/PlaceholderapiManager.java
> +public class PlaceholderapiManager extends PlaceholderExpansion {
actually, my original idea name it as "PlaceholderapiHandler.java", but I don't know where should I put it on
however, you are the original author of this plugin, I will respect your opinion

2023-09-30 10:29 UTC, alan67160 commented
@MartenM renamed, please check again

2023-10-02 07:14 UTC, alan67160 commented
@MartenM If I want to add a placeholder for check if the player has played the tutorial or not, do you think will it wold be better if a linkedhashmap added for caching? or just rely on hikari cache?

2023-10-02 07:25 UTC, alan67160 commented
idea is to on PlayerJoinEvent and TutorialEndEvent get data from mysql and save to linkedhashmap
on placeholder request get data from mysql

2023-10-02 11:50 UTC, MartenM commented
A hashmap would be preferable since placeholders should be resolved pretty quickly.
However, I would suggest waiting with this feature as I want to merge this simple one first!

2023-10-02 20:06 UTC, alan67160 commented
OK, then that will be my next new PR

2023-10-03 10:51 UTC, merged

2023-10-03 11:22 UTC, MartenM commented
I changed some things such that it makes more sense for the end users. Also moved the hooks to the API.
This has now been released https://www.spigotmc.org/resources/server-tutorial-plus.37741/update?update=518708

2023-10-03 11:55 UTC, alan67160 commented
ok, but just let you know If you return null to papi request, it will just replace to empty string automatically

2023-10-03 15:13 UTC, MartenM commented
When returning null I got just the placeholder but no replacement which might confuse users.
It won't replace it, since it doesn't know it should or should not replace it.